{{- with .Values }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .name }}-node
  labels:
    app: {{ .name }}-node
spec:
  selector:
    matchLabels:
      app: {{ .name }}-node
  template:
    metadata:
      labels:
        app: {{ .name }}-node
    spec:
      containers:
        #Node
        - name: {{ .name }}-node
          image: {{ .image }}
          env:
            - name: CSI_ENDPOINT
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
            - name: CSI_MODE
              value: node
          envFrom:
            - configMapRef:
                name: {{ .name }}-config
          volumeMounts:
            - name: socket
      volumes:
        - name: socket
          emptyDir: {}
{{- end }}
