# Default values for kube-xcpng-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: xcpng-csi
image: arturoguerra/xcpng-csi:latest
config: xcpng-csi-config
