kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xcpng-csi-role
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: xcpng-csi
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: xcpng-csi-runner
  apiGroup: rbac.authorization.k8s.io
