{{- with .Values }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-controller
  labels:
    app: {{ .name }}-controller
spec:
  selector:
    matchLabels:
      app: {{ .name }}-controller
  template:
    metadata:
      labels:
        app: {{ .name }}-controller
    spec:
      serviceAccount: xcpng-csi
      containers:
        # CSI Provisioner
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.5.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--enable-leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
        # CSI Attacher
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.1.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
        # Controller
        - name: {{ .name }}-controller
          image: {{ .image }}
          env:
            - name: XCPNG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .secret }}
                  key: xcpng-password
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: /var/lib/csi/sockets/pluginproxy/xcpng.socket
            - name: CSI_MODE
              value: controller
          envFrom:
            - configMapRef:
                name: {{ .config }}
          volumeMounts:
            - name: socket
              mountPath: /var/lib/csi/sockets/pluginproxy
      # Will only be scheduled on a master node
      nodeSelector:
        node-role.kubernetes.io/master: ""
      volumes:
        - name: socket
          emptyDir: {}
{{- end }}
