{{- if not .Values.configName }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "name" . }}
    namespace: {{ template "namespace" . }}
data:
{{ toYaml .Values.config | indent 4 }}
{{- end }}