apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: test-0
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
